config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 255}
    validates :status, presence: true, length: { maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email.downcase!}
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    private
    def require_user_logged_in
       unless logged_in?
        redirect_to login_url
       end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインできました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    
    before_action :require_user_logged_in
    before_action :correct_user, only: [:destroy, :update, :edit, :show]
    
    def index
        if logged_in?
            @tasks = current_user.tasks.order(id: :desc).page(params[:page])
        end
    end
    
    def create
        @task = current_user.tasks.build(task_params)
        if @task.save
            flash[:success] = "Taskが正常に登録されました"
            redirect_to @task
        else
            flash.now[:danger] = "Taskが登録出来ていません"
            render :new
        end
    end
    
    def new
        @task = Task.new
    end
    
    def edit
    end
    
    def show
       
    end
    
    def update
        if @task.update(task_params)
            flash[:saccess] = 'Taskが正常に編集されました'
            redirect_to @task
        else
            flash.now[:danger] = 'Taskが編集出来ていません'
            render :edit
        end
    end
    
    def destroy
        @task.destroy
        
        flash[:success] = "Taskは削除されました"
        redirect_to tasks_url
    end
    
    private
    def set_task
        @task = Task.find(params[:id])
    end
    
    def task_params
        params.require(:task).permit(:content,:status, :user)
    end
    
    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザーの登録に成功しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました"
      render :new
    end
  end

  def new
    @user = User.new
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||=User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
    <div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Tasklist</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item"><%= link_to  '新規Taskの登録', new_task_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        <li class="nav-item"><%= link_to 'Log in', login_path,class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Sign up', signup_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_tasks' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
    <div class="col-sm-6">
    <%= form_with(model: task, local: true) do |f| %>
        <% if task.errors.any? %>
            <div id="error_explanation" class="alert alert-warning">
                <ul class="mb-0">
                    <% task.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        <% end %>
        <div class="form-group">
            <%= f.label :status, 'ステータス' %>
            <%= f.text_field :status %>
        </div>
        <div class="form-group">
            <%= f.label :content, 'タスク' %>
            <%= f.text_field :content %>
        </div>
        <%= f.submit '登録' , class: 'btn btn-primary'%>
    <% end %>
    </div>
</div>

app/views/tasks/edit.html.erb
<h1><%= @task.id %>のTask編集ページ</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>
    <h1><%= current_user.name %>のTask一覧ページ</h1>
    
 
    
    <% if @tasks.any? %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>id</th>
                <th>status</th>
                <th>task</th>
            </tr>
        </thead>
        <tbody>
            <% @tasks.each do |task| %>
            <tr>
                <td><%= link_to task.id, task %></td>
                <td><%= task.status %></td>
                <td><%= task.content %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <% end %>
    
<div>
    <%= paginate @tasks %>
</div>
<%= link_to '新規Taskの登録', new_task_path, class: 'btn btn-primary' %>

<% else %>
    <div class="center jumbotron">
        <div class="text-center">
          <h1>Welcome to the Tasklist</h1>
          <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
        </div>
    </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Task新規作成ページ</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<% if logged_in? %>
    
    <h1><%= current_user.name %> のid: <%= @task.id %>のTask詳細ページ</h1>
    
        <table class="table table-bordered">
            
                <tr>
                    <th scope="row">id</th>
                    <td><%= @task.id %></td>
                </tr>
                <tr>
                    <th scope="row">status</th>
                    <td><%= @task.status %></td>
                </tr>
                <tr>
                    <th scope="row">task</th>
                    <td><%= @task.content %></td>
                </tr>
        </table>
    
    
    <%= link_to 'このTaskを編集する', edit_task_path(@task), class: 'btn btn-light' %>
    <%= link_to 'このTaskを削除する', @task, method: :delete, data: {confirm: '本当に削除してよろしいでしょうか？'}, class: 'btn btn-danger' %>
<% else %>
    <%= render 'sessions/new' %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
    <h1>sign up</h1>
</div>

<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :name, 'Name' %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :email, 'Email' %>
                <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :password, 'Password' %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation, 'Confirmation' %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
    </div>
</div>